--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/STCraftNetwork/DiscordLink
build-by-default: true
branches:
- main
projects:
  DiscordLink:
    libs:
      - src: jaxkdev/discordbot
        version: ^3.0.5
    path: ""
...
